### ISSUE TITLE
Warning al asignar regla a contextos.

### ISSUE THREAD

**Issue by juacas** [UNIMOODLE/moodle-local_notificationsagent#103]
Al asignar una regla a contextos obtengo este Warning:
![image](https://github.com/UNIMOODLE/moodle-local_notificationsagent/assets/1656180/a7b92f75-d071-4345-bc48-fdb83dbd0e81)

<html>
<body>
<font size="1" style="box-sizing: border-box; color: rgb(0, 58, 112); font-family: Inter, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br class="Apple-interchange-newline">
( ! ) Warning: Attempt to read property "shortname" on bool in /var/www/html/moodle40/local/notificationsagent/classes/rule.php on line 2246
--

1 | 0.0001 | 361560 | {main}( ) | .../index.php:0
2 | 0.2615 | 7404192 | local_notificationsagent\rule::get_coursename_and_username_by_rule_id( $ruleid = '6' ) | .../index.php:207

</font><span style="color: rgb(0, 58, 112); font-family: Inter, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"></span><div class="d-flex mb-4" style="box-sizing: border-box; display: flex !important; margin-bottom: 1.5rem !important; color: rgb(0, 58, 112); font-family: Inter, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><button type="button" class="btn btn-outline-primary importtemplate d-block mr-3" data-toggle="modal" data-target="#importTemplateModal" style="box-sizing: border-box; border-radius: 0.25rem; margin-top: 0px; margin-right: 1rem !important; margin-bottom: 0px; margin-left: 0px; font-family: inherit; font-size: 1rem; line-height: 1.5; overflow: visible; text-transform: none; appearance: button; display: block !important; font-weight: 400; color: rgb(11, 31, 76); text-align: center; vertical-align: middle; user-select: none; background-color: transparent; border: 1px solid rgb(3, 14, 175); padding: 0.375rem 0.75rem; transition: color 0.15s ease-in-out 0s, background-color 0.15s ease-in-out 0s, border-color 0.15s ease-in-out 0s, box-shadow 0.15s ease-in-out 0s; cursor: pointer;">Import</button><a href="http://moodle3.local/moodle40/local/notificationsagent/editrule.php?courseid=1&amp;action=add&amp;type=1" class="btn btn-outline-primary mr-3" style="box-sizing: border-box; color: rgb(11, 31, 76); text-decoration: none; background-color: transparent; transition: color 0.15s ease-in-out 0s, background-color 0.15s ease-in-out 0s, border-color 0.15s ease-in-out 0s, box-shadow 0.15s ease-in-out 0s; display: inline-block; font-weight: 400; text-align: center; vertical-align: middle; user-select: none; border: 1px solid rgb(3, 14, 175); padding: 0.375rem 0.75rem; font-size: 1rem; line-height: 1.5; border-radius: 0.25rem; margin-right: 1rem !important; cursor: pointer;">New rule</a><a href="http://moodle3.local/moodle40/local/notificationsagent/editrule.php?action=add&amp;type=0" class="btn btn-outline-primary mr-3" style="box-sizing: border-box; color: rgb(11, 31, 76); text-decoration: none; background-color: transparent; transition: color 0.15s ease-in-out 0s, background-color 0.15s ease-in-out 0s, border-color 0.15s ease-in-out 0s, box-shadow 0.15s ease-in-out 0s; display: inline-block; font-weight: 400; text-align: center; vertical-align: middle; user-select: none; border: 1px solid rgb(3, 14, 175); padding: 0.375rem 0.75rem; font-size: 1rem; line-height: 1.5; border-radius: 0.25rem; margin-right: 1rem !important; cursor: pointer;">New template</a><a href="http://moodle3.local/moodle40/local/notificationsagent/report.php" class="btn btn-outline-primary mr-3" style="box-sizing: border-box; color: rgb(11, 31, 76); text-decoration: none; background-color: transparent; transition: color 0.15s ease-in-out 0s, background-color 0.15s ease-in-out 0s, border-color 0.15s ease-in-out 0s, box-shadow 0.15s ease-in-out 0s; display: inline-block; font-weight: 400; text-align: center; vertical-align: middle; user-select: none; border: 1px solid rgb(3, 14, 175); padding: 0.375rem 0.75rem; font-size: 1rem; line-height: 1.5; border-radius: 0.25rem; margin-right: 1rem !important; cursor: pointer;">Reports</a><div class="d-flex flex-wrap ml-auto align-items-end" style="box-sizing: border-box; display: flex !important; flex-wrap: wrap !important; align-items: flex-end !important; margin-left: auto !important;"><button type="button" id="applyordergroupbtn" class="btn btn-outline-primary mr-3" style="box-sizing: border-box; border-radius: 0.25rem; margin-top: 0px; margin-right: 1rem !important; margin-bottom: 0px; margin-left: 0px; font-family: inherit; font-size: 1rem; line-height: 1.5; overflow: visible; text-transform: none; appearance: button; display: inline-block; font-weight: 400; color: rgb(11, 31, 76); text-align: center; vertical-align: middle; user-select: none; background-color: transparent; border: 1px solid rgb(3, 14, 175); padding: 0.375rem 0.75rem; transition: color 0.15s ease-in-out 0s, background-color 0.15s ease-in-out 0s, border-color 0.15s ease-in-out 0s, box-shadow 0.15s ease-in-out 0s; cursor: pointer;">Order by</button></div></div><br class="Apple-interchange-newline">
</body>
</html>

**Comment by fpano** [comment]
Ver #105
