### ISSUE TITLE
Rendimiento del selector de contextos con muchos cursos

### ISSUE THREAD

**Issue by juacas** [UNIMOODLE/moodle-local_notificationsagent#104]
Los interfaces similares a:
![image](https://github.com/UNIMOODLE/moodle-local_notificationsagent/assets/1656180/2c53ee88-7604-4e15-ad89-a205d7db4689)

/local/notificationsagent/index.php

Han generado problemas de escalabilidad en otros proyectos UNIMOODLE.
Necesitamos probar su funcionamiento con estructuras de miles de cursos y cientos de categorías.

**Comment by tmas0** [comment]
Buenas @fpano,

Reabro este ticket ya que nos estamos encontrando con un problema, y es que a la hora de crear una nueva regla en un contexto dónde hay muchas (+1.000) reglas, al dar a Nueva regla, el sistema responde de forma exageradamente lenta.

Ese caso no lo revisamos en la otra batida, y ahora nos está generando problemas.

La página tarda más de 10 segundos en responder.

Un saludo

**Comment by fpano** [comment]
Hola,
¿El problema es con cualquier regla o con alguna configuración de condiciones en concreto?

**Comment by fpano** [comment]
Ver #105
