### ISSUE TITLE
Visibilidad de las asignaciones de contexto.

### ISSUE THREAD

**Issue by juacas** [UNIMOODLE/moodle-local_notificationsagent#105]
Como el interfaz de asignación usa elementos "collapsibles" y solo uno está expandido en cada momento, no se puede ver dónde hay asignaciones hechas. Esto hace el interfaz inutilizable para una instalación de tamaño medio/grande.

La solución más obvia es que las categorías que tengan algún elemento marcado se destaquen con el checkbox en "gris" o de otra forma similar.

**Comment by LuksAO** [comment]
Propongo los siguientes posibles cambios en la interfaz de asignación a nivel de UX:

- Indicar en cada categoría el número de cursos y categorías que tiene seleccionados (o al menos algún indicativo de que hay cursos o categorías seleccionados dentro)

![image](https://github.com/UNIMOODLE/moodle-local_notificationsagent/assets/43584301/8c7a1345-7c99-43eb-808c-d1655d4f958c)

- Cuando se marque una categoría, que sus checkboxes hijos se deshabiliten.
    - Ahora mismo cuando se marca una categoría, te permite seguir seleccionando el contenido interior, esto creo que presta a confusión porque ya le estamos asignando la regla a un contexto superior por lo que aunque deseleccionemos un curso o categoría interior se le va a aplicar la regla igualmente.

![image](https://github.com/UNIMOODLE/moodle-local_notificationsagent/assets/43584301/dac88cdd-05aa-49b2-9b03-9dedd466ba8c)

- A raíz del anterior cambio sería conveniente mover la funcionalidad que tienen ahora mismo las categorías para marcar todos los cursos a un botón aparte.

![image](https://github.com/UNIMOODLE/moodle-local_notificationsagent/assets/43584301/9962cdb2-99b9-48f1-90af-f64e34dd9ad9)

**Comment by fpano** [comment]
En los últimos commits hemos modificado el comportamiento del modal para como comentaba @juacas , pero hemos tenido en cuanta lo mencionado por @LuksAO y lo comentado por @tmas0 en #103 y también ajustes para mejorar el rendimiento a la hora de asignar cuando hay muchas categorías.
