### ISSUE TITLE
Etiqueta de regla "Inválida" en regla forzada

### ISSUE THREAD

**Issue by juacas** [UNIMOODLE/moodle-local_notificationsagent#111]
Al forzar una regla desde administración, aparece correctamente instalada en el curso pero con la etiqueta "Inválida".
No sé si es un glich de presentación o está incumpliendo alguna restricción.
En el ejemplo, debería autoconfigurarse porque la acción se refiere al foro de "Novedades".

He comprobado que el estado "inválida" sale cuando el curso tiene o no tiene habilitada una fecha de finalización.

![image](https://github.com/UNIMOODLE/moodle-local_notificationsagent/assets/1656180/a5c55cf4-1847-4e2c-98fe-472092c8f8d5)

**Comment by fpano** [comment]
Corregida en el PR y añadido también test unitario sobre el método.
