### ISSUE TITLE
Mejora: Las condiciones de las reglas se comprueban con 'OR' o 'AND'?

### ISSUE THREAD

**Issue by LuksAO** [UNIMOODLE/moodle-local_notificationsagent#114]
En la UI debería estar aclarado, al menos en la interfaz de edición de una regla, si las condiciones se comprueban en la práctica con un 'OR' o un 'AND' a nivel de lógica, así como las excepciones.

También estaría bien poder elegir si querer usar 'AND' o 'OR'  e incluso poder mezclarlos, así como está hecho en la sección "Restricciones de acceso" en la configuración individual de los módulos de los cursos.

**Comment by fpano** [comment]
La regla sigue la siguiente lógica para su evaluación:

[Cond1] AND [Cond2] AND ... AND NOT ([Exc1] OR [Exc2] ...) -> [Action1]->[Action2]

**Comment by juacas** [comment]
Se ha diseñado así por sencillez del interfaz. En caso de que sea confuso se puede decorar el interfaz con algún elemento aclaratorio como puede ser insertar "And" entre cada condición y "Or" entre las excepciones. El problema es que aumenta el tamaño de la tarjeta de regla.
Otra opción es editar el texto de la ficha como en el ejemplo:
![image](https://github.com/UNIMOODLE/moodle-local_notificationsagent/assets/1656180/fe116130-dfc1-4005-a9d3-1a1cd53190f7)

En cualquier lo ratifico como "Enhancement".

**Comment by fpano** [comment]
Hemos cambiado las traducciones de las strings para que se entienda un poco mejor como sugería @juacas y añadido un tip de ayuda en la interfaz como decía @LuksAO para especificar la lógica de evaluación de la regla. Esta manera nos parecía la menos intrusiva.
