### ISSUE TITLE
BUG: Los profesores pueden editar dentro de sus cursos reglas definidas a nivel de sistema

### ISSUE THREAD

**Issue by LuksAO** [UNIMOODLE/moodle-local_notificationsagent#117]
1. Crear regla desde la interfaz de administración con un usuario admin
2. Asignar la regla a "Curso X"
3. Cerrar sesión e iniciar sesión como un profesor del "Curso X"
4. Si vamos a "Mi asistente" dentro del curso podemos editar la regla definida por el administrador lo cual afecta a todo el sitio

Posibles mejoras UX relativas a esto:
- Si no tienes permitido editar o pausar una regla sería mejor que los botones no estén o aparezcan como disabled.
- Las reglas definidas a nivel de sitio deberían tener algún elemento para diferenciarlas del resto en la interfaz de "Mi asistente" en los cursos, como un color de fondo distinto o un badge de bootstrap adicional.

**Comment by fpano** [comment]
Gracias por el aviso @LuksAO . Es un comportamiento anómalo provocado por un error en las queries que ya hemos corregido.
