### ISSUE TITLE
¿Las reglas no se crean tras backup?

### ISSUE THREAD

**Issue by LuksAO** [UNIMOODLE/moodle-local_notificationsagent#122]
local_notificationsagent commit: f05dbbdb4863d8695e48346ef96721fcf5f9fbc0
Moodle version: 4.1.11+ (Build: 20240614)

Cuando creas una copia de seguridad en un curso, descargas el archivo, y lo restauras en otro curso con la opción "Borrar el contenido del curso actual y después restaurar", no crea las <del>tareas</del> reglas del curso origen y tampoco borra las preexistentes.

**Comment by fpano** [comment]
> ,no crea las tareas del curso origen y tampoco borra las preexistentes.

¿A qué tareas te refieres @LuksAO?

**Comment by LuksAO** [comment]
Perdón, puse `tareas` pero quería decir `reglas`.

**Comment by fpano** [comment]
Revisando la issue hemos visto que para que copie las reglas del curso origen es necesario marcar la opción 
![image](https://github.com/user-attachments/assets/e264ee06-2f7f-4463-8e0f-20be0be00894)
como Yes.

Revisamos el borrado de la reglas preexistentes.

**Comment by LuksAO** [comment]
@fpano Hola efectivamente si marcamos esa opción si se copian las reglas.

Relativo a esto, considero que estaría más correcto si existiera un checkbox explícito para indicar si se quieren copiar las reglas o no, bien en esa misma parte de `Schema`o en `Settings`.

El input de `Overwrite course configuration` se refiere a la configuración del curso que está en la pestaña `Configuración`  del menú del curso, que realmente no está relacionado con el plugin de notificaciones.

**Comment by juacas** [comment]
El comportamiento por defecto de Moodle es el siguiente:
- Copia/restauración con datos de usuario: incluye toda la información asociada personalmente a los usuarios enrolados (estudiantes o profesores)
- Copia/resturación, en todos los casos: incluye toda la información asociada al curso.

En nuestro caso:
- información asociada al curso: reglas creadas o asignadas por administradores o profesores al contexto de curso.
- Información personal: reglas creadas por usuarios que solo afecten al propio individuo (reglas personales).

No debemos añadir ninguna opción adicional salvo que haya un argumento muy fuerte relacionado con la seguridad. En todo caso podemos añadir un capability específico que regule si un usuario puede restaurar reglas de curso o no.

**Comment by fpano** [comment]
Solucionada en el último commit.
