### ISSUE TITLE
invalid lang string file

### ISSUE THREAD

**Issue by danmarsden** [UNIMOODLE/moodle-local_notificationsagent#123]
The lang file is not really a "PHP" file - it should only contain simple strings and no PHP code.

eg the following is not correct:
$string['test'] = "sometext"."somemoretext";
or
$string['test'] = "sometext".$string['someotheritem'];

or
$string['asfd'] = "This".get_string("andthis");

each string must be contained within one set of quotes eg:
$string['test'] = "sometext somemoretext";

**Comment by fpano** [comment]
Fixed in the last commit. Thank you for the explanation @danmarsden  :)
