### ISSUE TITLE
PHP Unit tests de Moodle Core fallan si el plugin está instalado

### ISSUE THREAD

**Issue by LuksAO** [UNIMOODLE/moodle-local_notificationsagent#126]
### Versiones
Moodle 4.1.14+ (Build: 20241018), a6117d4b44439ef7590192d6f3a2914275af95f3
Php: 8.1.27, pgsql: 16.1 (Debian 16.1-1.pgdg120+1), OS: Linux 5.15.133.1-microsoft-standard-WSL2 x86_64
PHPUnit 9.5.28 by Sebastian Bergmann and contributors.

---

Ejecuto test de Moodle sin el plugin: Sin Errores
Ejecuto `vendor/bin/phpunit --group notificationsagent`: Sin Errores
Ejecuto test de Moodle con el plugin: 
- `php -d extension=uopz.so vendor/bin/phpunit | tee phpunit.log`
-  Encontró 187 errores

Los test parecen fallar debido a la función `notificationscondition_itemgraded_observer::user_graded`, al ser un evento este también es llamado por las funciones del core de Moodle.

Adjunto fichero con al salida de los unittests.

[phpunit.log](https://github.com/user-attachments/files/17541827/phpunit.log)

**Comment by fpano** [comment]
¡Hola!
Lo hemos solucionado en los últimos cambios subidos.
