### ISSUE TITLE
Uso ineficiente de queries a la base de datos

### ISSUE THREAD

**Issue by juacas** [UNIMOODLE/moodle-local_notificationsagent#24]
Por ejemplo, en:

https://github.com/UNIMOODLE/moodle-local_notificationsagent/blob/022ad174a06e80d477d367428ff42182f2998f10/condition/activitycompleted/classes/observer.php#L54

- Se hacen dos consultas para borrar un registro.
- La comprobación no es necesaria porque la función delete_records borrará lo que coincida con las condiciones. Si hay alguna excepción es preferible usar try...catch mejor que aumentar la presión a la base de datos.
- Este bloque se puede sustituir por una query con un  "conditionid IN (A, B, C, D, E)"

Es importante minimizar las consultas a la base de datos dado que este módulo va a generar una gran carga en sites grandes.

**Comment by fpano** [comment]
Buenas, 
hemos convertido el activitystudentend a un objeto persistente, también el sessionstart que le ocurría lo mismo.
