### ISSUE TITLE
Regla de estudiante no ejecutada y vista de estudiante sin acceso a los informes de reglas propias

### ISSUE THREAD

**Issue by juacas** [UNIMOODLE/moodle-local_notificationsagent#98]
He creado una regla con un usuario con rol estudiante.
Escenario:
- usuario Twitter 01 estudiante crea la regla: " If: The user has completed the activity Entrega de prueba. Then: Send notification to user twiter 01 with title Hay actividad completada and message {User_FirstName} ..."
- El profesor crea una regla idéntica con la misma condición.
- El usuario Twitter 01 termina la tarea "Entrega de prueba".

Resultados:
-  Se ejecuta la regla del profesor.
-  No hay rastro de que se ejecute la regla del estudiante. No aparece en el log de reglas del sistema.
- El interfaz del estudiante no muestra un botón para mostrar los informes de la regla.
- El administrador no puede ver ni actuar en las reglas creadas por otras personas en un curso. Cuando un administrador entra en un curso debe ver todas las reglas (con una etiqueta con el nombre del propietario). Si no es así no se podrán resolver incidencias.

**Comment by fpano** [comment]
Ya está implementado que el estudiante pueda acceder al informe de sus reglas.

**Comment by fpano** [comment]
También que el admin pueda actuar sobre las reglas de otros usuarios.
